### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by furax124** [codeuk/klimt#6]
Start build.bat but don't work

**Comment by furax124** [comment]
> Start build.bat but don't work

On windows 11

**Comment by furax124** [comment]
> > Start build.bat but don't work
> 
> On windows 11

Send this error : package command-line-arguments
        imports fyne.io/fyne/v2/app
        imports fyne.io/fyne/v2/internal/driver/glfw
        imports fyne.io/fyne/v2/internal/driver/common
        imports fyne.io/fyne/v2/internal/painter/gl
        imports github.com/go-gl/gl/v3.2-core/gl: build constraints exclude all Go files in C:\Users\paypa\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20211210172815-726fda9656d6\v3.2-core\gl

**Comment by codeuk** [comment]
This error suggests that you don't have MingW installed which is required for the imported package ('fyne') to run. I listed in the projects README that this is required and where you can install it.

**Comment by furax124** [comment]
> This error suggests that you don't have MingW installed which is required for the imported package ('fyne') to run. I listed in the projects README that this is required and where you can install it.

Do you have discord or telegram for talk ? Idk how to do that I do go get its downloading all requirements but still doesn't work if you can come Discord or telegram plz

**Comment by codeuk** [comment]
I don't use either of those platforms anymore, sorry. You can simply look up a tutorial on how to download/install MingW on your desired platform.

**Comment by furax124** [comment]
> I don't use either of those platforms anymore, sorry. You can simply look up a tutorial on how to download/install MingW on your desired platform.

Well okay thx a lot can I modify src code ? For add features

**Comment by furax124** [comment]
> We both know that you only asked that so you can create your own version of it. The open source license I used for this project prohibits closed sourced changes to the source code, but you can create a fork of it on github using the 'fork' button and add your changes there. Do not just download the code and reupload it.

Okay thx bro i don't want skid it for know my friend want premium you know his price ?

**Comment by codeuk** [comment]
I don't know 'his' price. Are you asking how much I sell it for? if so, I don't really sell access to it.

**Comment by furax124** [comment]
> I don't know 'his' price. Are you asking how much I sell it for? if so, I don't really sell access to it.

Yeah the price of pro

**Comment by furax124** [comment]
> I don't know 'his' price. Are you asking how much I sell it for? if so, I don't really sell access to it.

Can I have the price of pro ?

**Comment by codeuk** [comment]
1 million billion dollars.

**Comment by furax124** [comment]
> 1 million billion dollars.

Lmao for real ?

**Comment by furax124** [comment]
> I don't know 'his' price. Are you asking how much I sell it for? if so, I don't really sell access to it.

Can you give me the price of pro ? The real

**Comment by furax124** [comment]
> 1 million billion dollars.

In the stealer there are a obfuscator ? For know if I add it or no
