### ISSUE TITLE
Optimization & protection issues

### ISSUE THREAD

**Issue by TaxMachine** [codeuk/klimt#9]
I'm reviewing the code and I've found some part of the code that leave me very suspicious about the origin of the source code.

Like this part for example (agent/memory.go)
![image](https://github.com/codeuk/klimt/assets/78520042/6ecab4db-68d1-4d9c-b633-69781d260f37)
The comments are in places chatGPT (or any other LLMs) usually puts comments in codes

Also, there's stuff that are not suppose to be there (agent/socket.go)
![image](https://github.com/codeuk/klimt/assets/78520042/d1c4b0a5-cd6a-4d8b-98fe-f6a90b1c4044)
That doesn't mean anything! UPX is a packer, not a compression algorithm. TCP is a structure for network packets. I'm not sure what its suppose to mean in this context, I thought maybe he meant compressing data sent through the socket, which makes sense. In that case you should use something like Zlib, gzip or LZMA.

I also wanted to point out, do NOT use base64 to encode strings at compile-time. AVs can detect those because it is NOT encryption but encoding. you should use ENCRYPTION like XOR, RC4 or any other cipher like AES or DES and generate random keys. Also you shouldn't use UPX because packers are detected and especially UPX since you can unpack packed executables simply by doing `upx.exe -d executable.exe`. Another problem with Go is that there's not a debug/release build preset, so you should make it compile with those flags to remove debugging symbols `go build -ldflags "-s -w"` and doing `strip.exe -X -S -s agent.exe` because without them, only using ghidra (or IDA) you can easily get those symbols to map out the assembly 
![image](https://github.com/codeuk/klimt/assets/78520042/1f2b5bc8-4fa3-4cf6-97de-a13f9792482f)
![image](https://github.com/codeuk/klimt/assets/78520042/a0171bbd-8397-462a-9a90-f38a7e8d6151)

In (agent/network.go) do not use ip-api.com since it detects VPNs. if the victim has a VPN, the website will not respond and will either crash the program or sending empty fields. Consider using only ipwhois.app/json/. You're loosing precious milliseconds by sending two requests just to get a nearby lake or river near the victim's city

For the browsers, don't write any kind of custom headers, just make a json or a csv, its easier to parse afterward.

I won't make any pull request to fix all of this but consider to look at these issues. There are also alot of issues with the structure of the code in general, maybe a refactor is needed.

**Comment by codeuk** [comment]
Thank you for your concerns.


> The comments are in places chatGPT (or any other LLMs) usually puts comments in codes

I don't know where you got this from or what you're getting at, I wrote this myself, including the parts that most people would skid for their 'own' projects, such as decryption and browser/discord stealing especially, etc.


> Also, there's stuff that are not suppose to be there (agent/socket.go)

Because in the screenshot it states it is yet to be added.


> That doesn't mean anything! UPX is a packer, not a compression algorithm. TCP is a structure for network packets. I'm not sure what its suppose to mean in this context, I thought maybe he meant compressing data sent through the socket, which makes sense. In that case you should use something like Zlib, gzip or LZMA.

It does, in fact, mean something, that's why I added it. It's used in the premium version to transfer compressed files, but as you said it wasn't optimal so I changed my compression algorithm.


> I also wanted to point out, do NOT use base64 to encode strings at compile-time. AVs can detect those because it is NOT encryption but encoding. you should use ENCRYPTION like XOR, RC4 or any other cipher like AES or DES and generate random keys. Also you shouldn't use UPX because packers are detected and especially UPX since you can unpack packed executables simply by doing upx.exe -d executable.exe. Another problem with Go is that there's not a debug/release build preset, so you should make it compile with those flags to remove debugging symbols go build -ldflags "-s -w" and doing strip.exe -X -S -s agent.exe because without them, only using ghidra (or IDA) you can easily get those symbols to map out the assembly

I'm aware, it was a quick implementation for release so that little Discord kids couldn't use their epic skills to search strings in the binary. None of my optimal malware is public, hence the premium/private versions of most of my projects that get sold.


> In (agent/network.go) do not use ip-api.com since it detects VPNs. if the victim has a VPN, the website will not respond and will either crash the program or sending empty fields. Consider using only ipwhois.app/json/. You're loosing precious milliseconds by sending two requests just to get a nearby lake or river near the victim's city

The private version uses rotating, self-hosted API's.


> For the browsers, don't write any kind of custom headers, just make a json or a csv, its easier to parse afterward.

Yeah this would be better I guess.


> I won't make any pull request to fix all of this but consider to look at these issues. There are also alot of issues with the structure of the code in general, maybe a refactor is needed.

It is needed but I don't work on the project anymore, haven't for a long time.

**Comment by TaxMachine** [comment]
> > The comments are in places chatGPT (or any other LLMs) usually puts comments in codes
> 
> I don't know where you got this from or what you're getting at, I wrote this myself, including the parts that most people would skid for their 'own' projects, such as decryption and browser/discord stealing especially, etc.

It may be because I don't really see grabbers with comments on github often but the way its written and the places of some of the comments in the project use the same patterns when you ask any LLM to make a code. You may be right but lets say you did use chatgpt, its not wrong to use it, since its good when you want to learn programming, but you have to credit it at least somewhere. 👍

**Comment by codeuk** [comment]
I can assure you that I wrote it all myself. I write scripts that are used in production for critical infrastructure in my country; therefore I generally try and comment my code for others to understand, as I work in team-like environments.

**Comment by TaxMachine** [comment]
I REALLY wonder why a british government cyber analyst is selling discord rat kek
